### PR TITLE
Fix shut down behavior of server

### LINKED ISSUE #34: Server cannot be terminated with Ctrl+C
It sometimes happens to me that the node server won't be actually terminated when pressing Ctrl+C.
Sometimes it works right away but often the only way of terminating the server is by killing the process.
This is especially annoying because Docker won't be able to stop the container gracefully either.
I'm running the node server on Ubuntu.
Is anyone else experiencing this problem?

### PR DESCRIPTION
**Pull request by johartl**
When calling `server.close()` the server won't actually shut down until all connections are terminated (which can take quite a while because of keep-alive). So let's keep track of open connections and close them before shutting down the server.
Fixes #34.

### CODE REVIEW

File: lib/pokemon-site.js [hunk 1]
```diff
@@ -24,11 +24,21 @@ class PokemonSite {
...
+    this._server.listen(config.listenPort, config.listenAddress, () => {
       console.log('Listening on %s:%d ...', config.listenAddress, config.listenPort)
     })
-    this._server = server
+
+    // Keep track of open connections
+    this.socketId = 0
+    this.sockets = {}
+    this._server.on('connection', (socket) => {
+      let socketId = ++this.socketId
```
Comment (WoH) [inline lib/pokemon-site.js]: Indexing starts at 1, is there a reason for this?

Comment (johartl) [reply lib/pokemon-site.js]: No. But I suppose there is also no reason why it would start with 0, or is there?
But anyways, if this is important to you I accept your wish for indices starting with 0. See the latest commit.

Comment (gyachdav) [reply lib/pokemon-site.js]: @johartl the importance is consistency. It is a common practice (and a best practice) to start indexing at 0. So unless you have a very good reason to divert from convention, it is best that you just stay with the current.

**Comment by johartl** [comment]
@WoH I think it is best practice to let the developer who created the pull request also merge it :)

**Comment by WoH** [comment]
I usually just submit them when I am ready and have someone else review and merge. 
I felt ready to merge since I was the only one assigned, I should have held back then, my bad.@johartl

**Comment by johartl** [comment]
No worries :)
